In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('sales_pipeline.csv')

In [3]:
df.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,20-10-2016,01-03-2017,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,25-10-2016,11-03-2017,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,25-10-2016,07-03-2017,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,25-10-2016,09-03-2017,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,25-10-2016,02-03-2017,517.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   object
 1   sales_agent     8800 non-null   object
 2   product         8800 non-null   object
 3   account         7375 non-null   object
 4   deal_stage      8800 non-null   object
 5   engage_date     8300 non-null   object
 6   close_date      6711 non-null   object
 7   close_value     6711 non-null   float64
dtypes: float64(1), object(7)
memory usage: 550.1+ KB

In [5]:
df['close_value'] = df['close_value'].where(df['close_value'].notna(), 0.0)

In [6]:
df.to_csv('sales_pipeline_new.csv', index=False)

In [7]:
df

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,20-10-2016,01-03-2017,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,25-10-2016,11-03-2017,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,25-10-2016,07-03-2017,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,25-10-2016,09-03-2017,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,25-10-2016,02-03-2017,517.0
...,...,...,...,...,...,...,...,...
8795,9MIWFW5J,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,0.0
8796,6SLKZ8FI,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,0.0
8797,LIB4KUZJ,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,0.0
8798,18IUIUK0,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,0.0
8799,8I5ONXJX,Versie Hillebrand,MG Advanced,NaN,Prospecting,NaN,NaN,0.0